name: Kubernetes Blue-Green Deployment

on:
  push:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io
  KUBERNETES_NAMESPACE: default

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build and push both versions
      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/streamlit-app:blue
            ${{ secrets.DOCKERHUB_USERNAME }}/streamlit-app:green
      
      # Set up kubeconfig
      - name: Configure Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      
      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          # Replace registry placeholder
          sed -i "s|\${DOCKER_REGISTRY}|${{ secrets.DOCKERHUB_USERNAME }}|g" k8s/deployments.yaml
          
          # Apply Kubernetes manifests
          kubectl apply -f k8s/deployments.yaml
          kubectl apply -f k8s/service.yaml
          
          # Run deployment script
          chmod +x ./deploy.sh
          ./deploy.sh