name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest
        
    # - name: Run linting
    #   run: |
    #     # Stop the build if there are Python syntax errors or undefined names
    #     # Exclude virtual environment directory and other common paths
    #     flake8 . \
    #       --count \
    #       --select=E9,F63,F7,F82 \
    #       --show-source \
    #       --statistics \
    #       --exclude=venv,venv_aise,.venv,build,dist,*.egg-info,__pycache__
        
    - name: Echo success
      run: echo "CI pipeline completed successfully!"
